-- MySQL Script generated by MySQL Workbench
-- 09/09/15 19:40:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Projeto_Hotel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Projeto_Hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Projeto_Hotel` DEFAULT CHARACTER SET utf8 ;
USE `Projeto_Hotel` ;

-- -----------------------------------------------------
-- Table `Projeto_Hotel`.`Hóspede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projeto_Hotel`.`Hóspede` (
  `ID_Hóspede` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nome` VARCHAR(50) NOT NULL COMMENT '',
  `CPF` VARCHAR(11) NOT NULL COMMENT '',
  `Data_Nascimento` DATE NOT NULL COMMENT '',
  `Telefone` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`ID_Hóspede`)  COMMENT '',
  UNIQUE INDEX `ID_Hóspede_UNIQUE` (`ID_Hóspede` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projeto_Hotel`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projeto_Hotel`.`Endereco` (
  `ID_Endereço` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ID_Hóspede` INT NOT NULL COMMENT '',
  `Rua` VARCHAR(30) NOT NULL COMMENT '',
  `Número` INT NOT NULL COMMENT '',
  `Bairro` VARCHAR(30) NOT NULL COMMENT '',
  `Cidade` VARCHAR(30) NOT NULL COMMENT '',
  `CEP` VARCHAR(8) NOT NULL COMMENT '',
  PRIMARY KEY (`ID_Endereço`)  COMMENT '',
  UNIQUE INDEX `ID_Endereço_UNIQUE` (`ID_Endereço` ASC)  COMMENT '',
  INDEX `ID_Hóspede_idx` (`ID_Hóspede` ASC)  COMMENT '',
  CONSTRAINT `ID_Hóspede_Endereço`
    FOREIGN KEY (`ID_Hóspede`)
    REFERENCES `Projeto_Hotel`.`Hóspede` (`ID_Hóspede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projeto_Hotel`.`Quarto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projeto_Hotel`.`Quarto` (
  `ID_Quarto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Diária` DOUBLE NOT NULL COMMENT '',
  `Capacidade_Hóspedes` INT NOT NULL COMMENT '',
  `Status` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ID_Quarto`)  COMMENT '',
  UNIQUE INDEX `ID_Quarto_UNIQUE` (`ID_Quarto` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projeto_Hotel`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projeto_Hotel`.`Produto` (
  `ID_Produto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nome` VARCHAR(45) NOT NULL COMMENT '',
  `Valor` DOUBLE NOT NULL COMMENT '',
  PRIMARY KEY (`ID_Produto`)  COMMENT '',
  UNIQUE INDEX `ID_Produto_UNIQUE` (`ID_Produto` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projeto_Hotel`.`Consumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projeto_Hotel`.`Consumo` (
  `ID_Consumo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ID_Quarto` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ID_Consumo`)  COMMENT '',
  UNIQUE INDEX `ID_Consumo_UNIQUE` (`ID_Consumo` ASC)  COMMENT '',
  INDEX `ID_Quarto_idx` (`ID_Quarto` ASC)  COMMENT '',
  CONSTRAINT `ID_Quarto_Consumo`
    FOREIGN KEY (`ID_Quarto`)
    REFERENCES `Projeto_Hotel`.`Quarto` (`ID_Quarto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projeto_Hotel`.`Ocupação`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projeto_Hotel`.`Ocupação` (
  `ID_Ocupação` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ID_Quarto` INT NOT NULL COMMENT '',
  `ID_Consumo` INT NOT NULL COMMENT '',
  `Data_Entrada` DATE NOT NULL COMMENT '',
  `Dias_Ocupados` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ID_Ocupação`)  COMMENT '',
  UNIQUE INDEX `ID_Ocupação_UNIQUE` (`ID_Ocupação` ASC)  COMMENT '',
  INDEX `ID_Quarto_idx` (`ID_Quarto` ASC)  COMMENT '',
  INDEX `ID_Consumo_idx` (`ID_Consumo` ASC)  COMMENT '',
  CONSTRAINT `ID_Quarto_Ocupação`
    FOREIGN KEY (`ID_Quarto`)
    REFERENCES `Projeto_Hotel`.`Quarto` (`ID_Quarto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_Consumo_Ocupação`
    FOREIGN KEY (`ID_Consumo`)
    REFERENCES `Projeto_Hotel`.`Consumo` (`ID_Consumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projeto_Hotel`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projeto_Hotel`.`Reserva` (
  `ID_Reserva` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ID_Hóspede` INT NOT NULL COMMENT '',
  `ID_Quarto` INT NOT NULL COMMENT '',
  `Data_Reserva` DATE NOT NULL COMMENT '',
  `Data_Expiração` DATE NOT NULL COMMENT '',
  PRIMARY KEY (`ID_Reserva`)  COMMENT '',
  UNIQUE INDEX `ID_Reserva_UNIQUE` (`ID_Reserva` ASC)  COMMENT '',
  INDEX `ID_Hóspede_idx` (`ID_Hóspede` ASC)  COMMENT '',
  INDEX `ID_Quarto_idx` (`ID_Quarto` ASC)  COMMENT '',
  CONSTRAINT `ID_Hóspede_Reserva`
    FOREIGN KEY (`ID_Hóspede`)
    REFERENCES `Projeto_Hotel`.`Hóspede` (`ID_Hóspede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_Quarto_Reserva`
    FOREIGN KEY (`ID_Quarto`)
    REFERENCES `Projeto_Hotel`.`Quarto` (`ID_Quarto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projeto_Hotel`.`Ocupação_Hóspedes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projeto_Hotel`.`Ocupação_Hóspedes` (
  `Ocupação_ID_Ocupação` INT NOT NULL COMMENT '',
  `Hóspede_ID_Hóspede` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Ocupação_ID_Ocupação`, `Hóspede_ID_Hóspede`)  COMMENT '',
  INDEX `fk_Ocupação_has_Hóspede_Hóspede1_idx` (`Hóspede_ID_Hóspede` ASC)  COMMENT '',
  INDEX `fk_Ocupação_has_Hóspede_Ocupação1_idx` (`Ocupação_ID_Ocupação` ASC)  COMMENT '',
  CONSTRAINT `fk_Ocupação_has_Hóspede_Ocupação1`
    FOREIGN KEY (`Ocupação_ID_Ocupação`)
    REFERENCES `Projeto_Hotel`.`Ocupação` (`ID_Ocupação`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ocupação_has_Hóspede_Hóspede1`
    FOREIGN KEY (`Hóspede_ID_Hóspede`)
    REFERENCES `Projeto_Hotel`.`Hóspede` (`ID_Hóspede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projeto_Hotel`.`Consumo_Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projeto_Hotel`.`Consumo_Produto` (
  `Consumo_ID_Consumo` INT NOT NULL COMMENT '',
  `Produto_ID_Produto` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Consumo_ID_Consumo`, `Produto_ID_Produto`)  COMMENT '',
  INDEX `fk_Consumo_has_Produto_Produto1_idx` (`Produto_ID_Produto` ASC)  COMMENT '',
  INDEX `fk_Consumo_has_Produto_Consumo1_idx` (`Consumo_ID_Consumo` ASC)  COMMENT '',
  CONSTRAINT `fk_Consumo_has_Produto_Consumo1`
    FOREIGN KEY (`Consumo_ID_Consumo`)
    REFERENCES `Projeto_Hotel`.`Consumo` (`ID_Consumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consumo_has_Produto_Produto1`
    FOREIGN KEY (`Produto_ID_Produto`)
    REFERENCES `Projeto_Hotel`.`Produto` (`ID_Produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
